### ISSUE TITLE
Looking at improving the UI of this birthday app

### ISSUE THREAD

**Issue by nnamdei** [nnamddyy/Happybirthday#1]
Looking at improving the UI of this birthday app and add it a few features for Android 8.1. Any ideas

**Comment by aelobdog** [comment]
What exactly does this app do? will be useful in the ui design process

**Comment by abdulgaphy** [comment]
can you explain what exactly it does? is it that it will take user input, i mean you type a name and it output it

**Comment by goyal-sakshi** [comment]
You could add birthday cliparts to it, as you have already used a RelativeLayout.

**Comment by nnamdei** [comment]
The app displays the photo of the celebrant and your birthday message as well.

**Comment by goyal-sakshi** [comment]
As you have told that you want to improve the UI of this app, you can do this by adding cliparts like - cake, birthday caps etc. To make it more attractive you can also add OnClickListners to these cliparts and open a new activity with more pictures of the celebrant.

**Comment by habeex** [comment]
You can add simple animation to improve the UI, that would look like story about the celebrant.

**Comment by nnamdei** [comment]
thanks guys. taken note of all your suggestion.
